<?php

// 
// function careertastic_agent_schema() {
  // $schema = array();
// 
  // $schema['agent_commissions'] = array(
    // 'description' => 'The base table for the Agent Commissions entity',
    // 'fields' => array(
      // 'transaction_id' => array(
        // 'description' => 'Primary key of the Commission entity',
        // 'type' => 'serial',
        // 'unsigned' => TRUE,
        // 'not null' => TRUE,
      // ),
      // 'coupon_id' => array(
        // 'description' => 'Coupon ID use on course purchase',
        // 'type' => 'varchar',
        // 'length' => 255,
        // 'not null' => FALSE,
      // ),
      // 'percentage' => array(
        // 'description' => 'Percentage of coupon use',
        // 'type' => 'int',
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
      // 'course_title' => array(
        // 'description' => 'Course Title',
        // 'type' => 'varchar',
        // 'length' => 255,
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
      // 'course_price' => array(
        // 'description' => 'Course Price',
        // 'type' => 'int',
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
      // 'commission' => array(
        // 'description' => 'Commission',
        // 'type' => 'int',
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
      // 'is_paid' => array(
        // 'description' => 'If it is paid or not',
        // 'type' => 'int',
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
      // 'date_created' => array(
        // 'description' => 'Date logged',
        // 'type' => 'int',
        // 'not null' => FALSE,
        // 'default' => NULL
      // ),
    // ),
    // 'primary key' => array('transaction_id'),
  // );
// 
  // return $schema;
// }
